### ISSUE TITLE
error while installing on windows 7

### ISSUE THREAD

**Issue by androidfreakers** [openshift/rhc#682]
I am facing problem while installing rhc on windows 7 machine. Here is log.

C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dl/impo
rt (LoadError)
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/pageant.rb:1:in `<top (required
)>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/agent/socket.rb:5:in `<top (req
uired)>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/agent.rb:22:in `<top (required)
>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/key_manager.rb:4:in `<top (requ
ired)>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/session.rb:4:in `<top (required
)>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:11:in `<top (required)>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/ssh_helpers.rb:18:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/wizard.rb:77:in `<class:Wizard>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/wizard.rb:7:in `<module:RHC>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/wizard.rb:6:in `<top (required)>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/commands/base.rb:4:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/commands/account.rb:2:in `<module:Commands>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/commands/account.rb:1:in `<top (required)>'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/commands.rb:189:in `block in load'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/commands.rb:188:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/commands.rb:188:in `load'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/lib/rhc/cli.rb:36:in `start'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/rhc-1.35.1/bin/rhc:20:in `<top (required)>'
        from C:/Ruby22/bin/rhc:23:in `load'
        from C:/Ruby22/bin/rhc:23:in `<main>'

**Comment by ariesy** [comment]
I have the same issue too.

**Comment by lem38** [comment]
Same for me. No news?

**Comment by tiwillia** [comment]
This is a duplicate of issue #679 

The temporary workaround is to install a specific version of the net-ssh gem: `v2.9.3.beta1` (confirmed working) or `2.9.2` (unconfirmed).

@danmcp we can close this duplicate.

**Comment by lcollet** [comment]
@tiwillia @danmcp 

let this issue open. Some others errors happen due to net-ssh 2.9.3.beta1.

See this issue : http://stackoverflow.com/questions/31906673/openshift-and-net-ssh-incompatibility-2-9-3-beta1-vs-2-9-2

What about an upgrade to new net-ssh 2.10.1.rc1 ?

**Comment by matteoferla** [comment]
Upgrading to 2.10.1.rc1 does not work as rhc accepts upto 2.9.3. I have not tried filing off the serial numbers or changing the dependency requirement.
I tried going back in time.
net-ssh 2.6.5 clashes with other modules.
Installing rhc 1.35.3, which lacks the upper version boundary does not work as something in the top module changed.
Installing rhc 1.35.4 (has boundary condition) and uninstalling the 2.9.2 it brings with it, gives the same.

**Comment by matteoferla** [comment]
If it helps, I ended up writing a
try/catch exception around most of my server-side py script and dump it on the document for JS to send to console.log. inelegant.

**Comment by lcollet** [comment]
Ruby 2.1.6 and net-ssh 2.9.2 solved my problem. (Downgrade from Ruby 2.2.2 to 2.1.6 and net-ssh 2.9.3-beta1 to 2.9.2)

**Comment by matteoferla** [comment]
@lcollet thanks! Your solution works a treat! If only GitHub has an upvote button...

**Comment by crezam** [comment]
@lcollet another thank you. I think the issue is more about Ruby 2.2.2, seems to work for either net-ssh, but there is also some issues in net-ssh maybe not related, to the point 2.9.3 was retired.
In summary, your advice is the best to follow. Ruby 2.2.2 and net-ssh 2.9.2 is the safest bet.

**Comment by zipzit** [comment]
Apparently there are problems with gems and windows install, as it affects the RHC tool. (Not sure how other operating systems are affected, but this is definite no go on windows 7) I can install Ruby and gems fine.. new install:

    $ ruby -v
    ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]

    $ gem -v
    2.4.5.1 

Apparently there are problems with net-ssh libraries... 

    $ rhc setup
    c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- dl/import (LoadError)
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/pageant.rb:1:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/agent/socket.rb:5:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/agent.rb:22:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/key_manager.rb:4:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/session.rb:4:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:11:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/ssh_helpers.rb:18:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/wizard.rb:77:in `<class:Wizard>'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/wizard.rb:7:in `<module:RHC>'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/wizard.rb:6:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/commands/base.rb:4:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/commands/account.rb:2:in `<module:Commands>'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/commands/account.rb:1:in `<top (required)>'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/commands.rb:189:in `block in load'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/commands.rb:188:in `each'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/commands.rb:188:in `load'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/lib/rhc/cli.rb:36:in `start'
        from c:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rhc-1.38.4/bin/rhc:20:in `<top (required)>'
        from c:/Ruby22-x64/bin/rhc:23:in `load'
        from c:/Ruby22-x64/bin/rhc:23:in `<main>'

Apparently a whole lot of people have this problem.  Here's an idea.  Is it possible, just possible to create command line tools in more functional, more robust language than ruby?  I've got a dead site, and no way to figure out why.  

http://stackoverflow.com/questions/33593856/rhc-setup-gives-error-no-such-file-dl-import-still
http://stackoverflow.com/questions/28896733/rhc-setup-gives-error-no-such-file-dl-import
http://stackoverflow.com/questions/30045486/rhc-setup-command-is-not-working?lq=1
http://stackoverflow.com/questions/28896733/rhc-setup-gives-error-no-such-file-dl-import?lq=1
http://stackoverflow.com/questions/29593646/error-setting-up-rhc-red-hat-client-tools?lq=1

I'm sure I could keep going on, but I'm hoping you get the point.  This just sucks.

**Comment by matteoferla** [comment]
Simply disinstall and use an only installer (from the site)[https://www.ruby-lang.org/en/downloads/].
One thing that is curious is that I had a very simple Python openshift site go down over the weekend (link)[http://battle-matteoferla.rhcloud.com/], but not a Django one. Pushing a commit of anything reset the server and it worked fine. I did not check why, but I think it is linked to the fact I could log in some days back too...

**Comment by kamakshi417** [comment]
same issue in win8

**Comment by david-mas** [comment]
It works using ruby 2.1.8 (which includes net-ssh 2.9.2)

**Comment by Alan-Liang** [comment]
@lcollet but why it is like this?
Thank you ***very*** much!
