### ISSUE TITLE
rhc setup error: `block in activate_dependencies': can't satisfy 'highline (~> 1.6.11)', already activated 'highline-1.7.1' (Gem::LoadError)

### ISSUE THREAD

**Issue by songgaoxian** [openshift/rhc#684]
The error message is as follows: 
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1206:in `block in activate_dependencies': can't satisfy 'highline (~> 1.6.11)', already activated 'highline-1.7.1' (Gem::LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1198:in `activate_dependencies'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/specification.rb:1180:in `activate'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:48:in `gem'
	from /usr/bin/rhc:22:in `<main>'

I installed rbenv from git and it seems that rhc setup use the system ruby. How to fix this error? I tried the method: gem install rubygems-update; rbenv rehash; update_rubygems; but it does not work for me. For rbenv rehash, the terminal shows "no such command"; for update_rubygems, it also shows "no such command". I don't know how to install shim or what shim is. As a new user of OSX, can anyone help me or give me some instructions?

**Comment by glesage** [comment]
Also getting this issue... unfortunately its also on a system where I cannot uninstall gems so attempting something like this http://stackoverflow.com/questions/19344049/block-in-activate-dependencies-cant-satisfy-windows-pr-1-2-1-already is not possible /:

I tried running this after also installing 1.7.2 but no luck.. same error /:

**Comment by truth3** [comment]
Hey guys, run an update on commander and this should resolve your troubles

**Comment by vinipsmaker** [comment]
It's a duplicate from issue #673
