### ISSUE TITLE
LoadError when running rhc setup command on Windows

### ISSUE THREAD

**Issue by johnwickers** [openshift/rhc#755]
Currently receiving the following load error message when running the `rhc setup` command:

```
C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::TimeoutError is deprecated
C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- dl/import (LoadError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/pageant.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/agent/socket.rb:5:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/agent.rb:22:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/key_manager.rb:4:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh/authentication/session.rb:4:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/net-ssh-2.9.2/lib/net/ssh.rb:11:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/ssh_helpers.rb:18:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/wizard.rb:77:in `<class:Wizard>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/wizard.rb:7:in `<module:RHC>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/wizard.rb:6:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/commands/base.rb:4:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/commands/account.rb:2:in `<module:Commands>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/commands/account.rb:1:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/commands.rb:189:in `block in load'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/commands.rb:188:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/commands.rb:188:in `load'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/lib/rhc/cli.rb:36:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rhc-1.38.4/bin/rhc:20:in `<top (required)>'
        from C:/Ruby23-x64/bin/rhc:23:in `load'
        from C:/Ruby23-x64/bin/rhc:23:in `<main>'
```

**Comment by DeepakUST** [comment]
Please help someone I am also facing same issue

**Comment by frcalan** [comment]
Friends had the same problem ... :(

Solution : Install the version 2.1.9!! :)

**Comment by tobiasschuerg** [comment]
same as #757

**downgrading is no solution**, just a workaround
