### ISSUE TITLE
Deprecation warnings about Object#Timeout

### ISSUE THREAD

**Issue by eazel7** [openshift/rhc#767]
The output of this warning is permanent. It is clogging the tubes.

My ruby version is: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]`

```
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
/home/eazel7/.gem/ruby/2.3.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
```

**Comment by notthetup** [comment]
Seeing so many of these warnings everywhere even with ruby 2.4.0. 

```
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::NIL is deprecated
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::TRUE is deprecated
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::FALSE is deprecated
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::Fixnum is deprecated
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::Bignum is deprecated
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::TimeoutError is deprecated
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:746:in `connect': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:950:in `read_body_length': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:616:in `query': Object#timeout is deprecated, use Timeout.timeout instead.
/Users/chinmay/.rvm/gems/ruby-2.4.0/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header': Object#timeout is deprecated, use Timeout.timeout instead.
```

I'm guessing updating dependencies for `commander` and `httpclient` to https://rubygems.org/gems/commander/versions/4.4.3 and https://rubygems.org/gems/httpclient/versions/2.8.3 respectively should help.

#744 tried to fix it but it seems it needs a rebase.

**Comment by tjnapster555** [comment]
@notthetup can your tell me how to fix this i see so many waring when i run rhc command in windows ?

**Comment by notthetup** [comment]
@tjnapster555 Check #744. That seems like a fix. I haven't checked it but makes sense based on the dependency version.

**Comment by tjnapster555** [comment]
@notthetup no the rhc command still show warring is there a way i can run rhc with **ruby warring** to set 0 or off ?

**Comment by notthetup** [comment]
@tjnapster555 Sorry I can't help you much with that. I am not a ruby programmer. @dydx is the author of #744 and might be able to help out.
